targetNamespace: ''
cleanNamespace: false
parameters: {}
environment:
  ENV: "${ENV}"
  VERBOSITY: "${VERBOSITY}"
  COURIER_AUTH_TOKEN: "${COURIER_AUTH_TOKEN}"
packages:
  - name: contact
    shared: false
    clean: false
    environment: {}
    parameters: {}
    actions:
      - name: newContact
        clean: false
        binary: false
        web: true
        webSecure: false
        annotations: {}
        main: ''
        runtime: 'go:default'
        parameters: {}
        environment: {}
