parameters: {}
environment: {}
packages:
  - name: contact
    environment: {}
    parameters: {}
    actions:
      - name: contact
        main: ''
        runtime: 'go:default'
        parameters: {}
        environment: {}
