parameters: {}
environment:
  ENV: "${VERBOSITY}"
  VERBOSITY: "${VERBOSITY}"
  COURIER_AUTH_TOKEN: "${COURIER_AUTH_TOKEN}"
packages:
  - name: contact
    environment: {}
    parameters: {}
    actions:
      - name: contact
        main: ''
        runtime: 'go:default'
        parameters: {}
        environment: {}
